# Generated by Django 3.2.6 on 2021-08-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vakation',
            old_name='timenow',
            new_name='timestap',
        ),
    ]
