# Generated by Django 3.2.6 on 2021-09-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_rename_timenow_vakation_timestap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestap', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='vakation',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.city'),
        ),
        migrations.AlterField(
            model_name='vakation',
            name='company',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vakation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vakation',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.language'),
        ),
        migrations.AlterField(
            model_name='vakation',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
