# Generated by Django 3.2.6 on 2021-09-16 17:15

from django.db import migrations
import jsonfield.fields
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errors',
            options={'verbose_name_plural': 'Errors'},
        ),
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name_plural': 'Urls'},
        ),
        migrations.AlterField(
            model_name='urls',
            name='data',
            field=jsonfield.fields.JSONField(default=scraping.models.default_urls),
        ),
    ]
