# Generated by Django 3.2.6 on 2021-09-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20210916_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vakation',
            options={'ordering': ['-timestap']},
        ),
    ]
